export const LOADING_MENU = 'LOADING_MENU';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';
export const LOAD_MENU_FAILURE = 'LOAD_MENU_FAILURE';

export const LOADING_TABLES = 'LOADING_TABLES';
export const LOAD_TABLES_SUCCESS = 'LOAD_TABLES_SUCCESS';
export const LOAD_TABLES_FAILURE = 'LOAD_TABLES_FAILURE';

export const SELECT_CHECK = 'SELECT_CHECK';
export const SELECT_TABLE = 'SELECT_TABLE';

export const LOAD_TABLE_CHECK = 'LOAD_TABLE_CHECK';
export const LOAD_TABLE_CHECK_SUCCESS = 'LOAD_TABLE_CHECK_SUCCESS';
export const LOAD_TABLE_CHECK_NOT_FOUND = 'LOAD_TABLE_CHECK_NOT_FOUND';
export const LOAD_TABLE_CHECK_FAILURE = 'LOAD_TABLE_CHECK_FAILURE';

export const LOADING_CHECKS = 'LOADING_CHECKS';
export const LOAD_CHECKS_SUCCESS = 'LOAD_CHECKS_SUCCESS';
export const LOAD_CHECKS_FAILURE = 'LOAD_CHECKS_FAILURE';

export const LOADING_CHECK = 'LOADING_CHECK';
export const LOAD_CHECK_SUCCESS = 'LOAD_CHECK_SUCCESS';
export const LOAD_CHECK_FAILURE = 'LOAD_CHECK_FAILURE';

export const CREATE_NEW_CHECK = 'CREATE_NEW_CHECK';
export const CREATE_NEW_CHECK_SUCCESS = 'CREATE_NEW_CHECK_SUCCESS';
export const CREATE_NEW_CHECK_FAILURE = 'CREATE_NEW_CHECK_FAILURE';

export const ADD_CHECK_ITEM = 'ADD_CHECK_ITEM';
export const ADD_CHECK_ITEM_SUCCESS = 'ADD_CHECK_ITEM_SUCCESS';
export const ADD_CHECK_ITEM_FAILURE = 'ADD_CHECK_ITEM_FAILURE';

export const VOID_CHECK_ITEM = 'VOID_CHECK_ITEM';
export const VOID_CHECK_ITEM_SUCCESS = 'VOID_CHECK_ITEM_SUCCESS';
export const VOID_CHECK_ITEM_FAILURE = 'VOID_CHECK_ITEM_FAILURE';

export const CLOSE_CHECK = 'CLOSE_CHECK';
export const CLOSE_CHECK_SUCCESS = 'CLOSE_CHECK_SUCCESS';
export const CLOSE_CHECK_FAILURE = 'CLOSE_CHECK_FAILURE';
